name: SpotBugs Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: SpotBugs Plugin
        run: mvn spotbugs:check  
      - name: upload SARIF file as artifact
        uses: actions/upload-artifact@v4
        with:
	      name: spotbugs-results.sarif
	      path: target/spotbugsSarif.json
      - name: Upload SARIF file to GitHub
	    uses: github/codeql-action/upload-sarif@v3
	    # continue-on-error: true
	    with:
	      # Path to SARIF file relative to the root of the repository
	      sarif_file: target/spotbugsSarif.json
